<div class="fof-blogs-container row"><div class="col col-lg-4 col-md-12 blog-container"><div class="blog-image-container" style="background: url(&quot;../../../themes/velocity/assets/images/blog-1.jpg&quot;) center center / cover no-repeat;"><a href="/page/loyality-programm"></a></div> <div class="blog-title"><a href="/page/loyality-programm">Программа лояльности</a></div> <div class="blog-desc">

Мы разработали удобную программу лояльности, которая позволит Вам экономить на покупках в нашем...
      </div></div> <div class="col col-lg-4 col-md-12 blog-container"><div class="blog-image-container" style="background: url(&quot;https://cdn.shopify.com/s/files/1/1002/2818/files/56905092_2788110764562212_2422688797092216832_o_grande.jpg?v=1598341915&quot;) center center / cover no-repeat;"><a href="/page/the-story"></a></div> <div class="blog-title"><a href="/page/the-story">THE STORY OF 'DARK MOON HYDRATING CREAM'</a></div> <div class="blog-desc">
        A little know T&amp;amp;D fact is that &amp;lsquo;Dark Moon&amp;rsquo; &amp;ndash; our intense, deep hydrating,...
      </div></div> <div class="col col-lg-4 col-md-12 blog-container"><div class="blog-image-container" style="background: url(&quot;https://cdn.shopify.com/s/files/1/0109/3302/products/karekare2_grande_grande_2c706dfa-cd2f-4292-8e0b-6f01cd6e6de2_large.jpg?v=1580435083&quot;) center center / cover no-repeat;"><a href="/page/karekare"></a></div> <div class="blog-title"><a href="/page/karekare">THE STORY OF 'KAREKARE TONIC'</a></div> <div class="blog-desc">

Karekare beach can be duplicitous, at times a brooding, wind-swept, malevolent beast, at others...
      </div></div></div>
